Select * from Customer limit 20
--Q1 What id=s the total revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer group by gender
--Q2 Which customer used a discount but still spent more then the average purchase amount ?
select customer_id,purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer  
GROUP BY item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, Round(AVG(purchase_amount),2)
from customer 
where shipping_type in ('Standard','Express')
group by (Shipping_type);

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customers,
round(Avg(purchase_amount),2) as Avg_Spend,
round(sum(purchase_amount),2) as Total_Revenue 
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100 * sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer 
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
Select customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment , count(*) AS "Number of Customer"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
with item_counts as (
select category,item_purchased,
count(customer_id) as Total_orders,
ROW_NUMBER()over(partition by category order by count (customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank,category,item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 

select age_group, Sum(purchase_amount) AS total_revenue from customer
group by age_group
order by total_revenue desc;